<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="ru"><head><meta charset="UTF-8"><title>Аудитории</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/css/app.css"></head>
<body><main class="page"><section class="hero"><div><h1>Аудитории</h1><p>Добавление, редактирование и удаление аудиторий.</p></div><nav class="top-nav"><a href="${pageContext.request.contextPath}/groups">Группы</a><a href="${pageContext.request.contextPath}/schedule">Расписание</a></nav></section>
<section class="grid"><div class="panel"><h2>Список аудиторий</h2><table id="classrooms-table"><thead><tr><th>Номер</th><th>Вместимость</th><th>Факультет</th><th>Действия</th></tr></thead><tbody>
<c:forEach items="${classrooms}" var="classroom"><tr><td>${classroom.roomNumber}</td><td>${classroom.capacity}</td><td>${classroom.faculty.name}</td><td><form method="post" action="${pageContext.request.contextPath}/classrooms/${classroom.id}" class="inline-form"><input name="roomNumber" value="${classroom.roomNumber}"><input name="capacity" type="number" value="${classroom.capacity}"><select name="facultyId"><c:forEach items="${faculties}" var="faculty"><option value="${faculty.id}" <c:if test="${classroom.faculty.id == faculty.id}">selected</c:if>>${faculty.name}</option></c:forEach></select><button type="submit">Редактировать</button></form><form method="post" action="${pageContext.request.contextPath}/classrooms/${classroom.id}/delete"><button type="submit" class="button-danger">Удалить</button></form></td></tr></c:forEach>
</tbody></table></div><div class="panel"><h2>Добавить аудиторию</h2><form id="classroom-form" method="post" action="${pageContext.request.contextPath}/classrooms" class="stack"><div><label>Номер аудитории</label><input name="roomNumber" required></div><div><label>Вместимость</label><input name="capacity" type="number" min="1" required></div><div><label>Факультет</label><select name="facultyId"><c:forEach items="${faculties}" var="faculty"><option value="${faculty.id}">${faculty.name}</option></c:forEach></select></div><button type="submit">Сохранить</button></form></div></section>
</main></body></html>
