<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="ru"><head><meta charset="UTF-8"><title>Группы</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/css/app.css"></head>
<body><main class="page"><section class="hero"><div><h1>Группы</h1><p>Добавление, редактирование и удаление учебных групп.</p></div><nav class="top-nav"><a href="${pageContext.request.contextPath}/students">Студенты</a><a href="${pageContext.request.contextPath}/classrooms">Аудитории</a></nav></section>
<section class="grid"><div class="panel"><h2>Список групп</h2><table id="groups-table"><thead><tr><th>Название</th><th>Год</th><th>Факультет</th><th>Действия</th></tr></thead><tbody>
<c:forEach items="${groups}" var="group"><tr><td>${group.name}</td><td>${group.studyYear}</td><td>${group.faculty.name}</td><td><form method="post" action="${pageContext.request.contextPath}/groups/${group.id}" class="inline-form"><input name="name" value="${group.name}"><input name="studyYear" type="number" value="${group.studyYear}"><select name="facultyId"><c:forEach items="${faculties}" var="faculty"><option value="${faculty.id}" <c:if test="${group.faculty.id == faculty.id}">selected</c:if>>${faculty.name}</option></c:forEach></select><button type="submit">Редактировать</button></form><form method="post" action="${pageContext.request.contextPath}/groups/${group.id}/delete"><button type="submit" class="button-danger">Удалить</button></form></td></tr></c:forEach>
</tbody></table></div><div class="panel"><h2>Добавить группу</h2><form id="group-form" method="post" action="${pageContext.request.contextPath}/groups" class="stack"><div><label>Название группы</label><input name="name" required></div><div><label>Год обучения</label><input name="studyYear" type="number" min="1" max="6" required></div><div><label>Факультет</label><select name="facultyId"><c:forEach items="${faculties}" var="faculty"><option value="${faculty.id}">${faculty.name}</option></c:forEach></select></div><button type="submit">Сохранить</button></form></div></section>
</main></body></html>
